name: Go

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags' 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.17'
      
    - run: go version

    - name: Show home dir
      run: |
        ls -l ~/

    - name: Create artifact directory
      run: |
        mkdir ~/artifact

    - name: Print working directory
      run: |
        pwd

    - name: Build
      run: go build -o ~/artifact
      
    - name: Show build
      run: |
        ls -l ~/artifact

    - name: Test
      run: go test ./...
      
    - uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: ~/artifact/
